### ISSUE TITLE
Fatal error on saving data

### ISSUE THREAD

**Issue by edewaele** [Cyrille37/yapafo#19]
Today, in Nomino, any attempt of saving data results in an error message, though the changeset is successfully sent to openstreetmap.org.

The _httpApi method seems to misinterpret the response from OSM.

PHP Fatal error:  Uncaught exception 'OSM_HttpException' with message 'HTTP/1.1 200 OK' in /home/pouf/nomino/lib/yapafo/lib/OSM/Api.php:277
Stack trace:
#0 /home/pouf/nomino/lib/yapafo/lib/OSM/Api.php(909): OSM_Api->_httpApi('changeset/25395...', NULL, 'PUT')
#1 /home/pouf/nomino/lib/yapafo/lib/OSM/Api.php(869): OSM_Api->_closeChangeSet(Object(OSM_Objects_ChangeSet))
#2 /home/pouf/nomino/api/osm_iface.php(214): OSM_Api->saveChanges('Place names tra...')

{main}
 thrown in /home/pouf/nomino/lib/yapafo/lib/OSM/Api.php on line 277, referer: http://localhost/nomino/index.php?oauth_token=Pdw5eyY8xwvIhQRzmYPRxcv9z91EK2ilGW5ijoBX&oauth_verifier=cfAutACrrSpKPzsP9UbO

**Comment by Cyrille37** [comment]
To old, I close this issue. Reopening a issue if needed ;-)
